media:
  input: assets/uploads
  output: /official-maranatha-website/assets/uploads
  categories: [image]
content:
  - name: posts
    label: Blogbeiträge
    type: collection
    path: _posts
    format: yaml-frontmatter
    filename: "{year}-{month}-{day}-{primary}.md"
    view:
      primary: title
      sort: date
      order: desc
    fields:
      - name: title
        label: Titel
        type: string
        required: true
      - name: date
        label: Datum
        type: date
        required: true
      - name: published
        label: Veröffentlicht
        type: boolean
        description: Ausschalten, um den Beitrag als Entwurf zu speichern.
      - name: author
        label: Autor
        type: string
      - name: description
        label: Kurzbeschreibung
        type: text
        required: true
      - name: image
        label: Titelbild
        type: image
      - name: image_alt
        label: Bildbeschreibung
        type: string
      - name: body
        label: Inhalt
        type: rich-text
        required: true
      - name: title_en
        label: "Title (English)"
        type: string
      - name: description_en
        label: "Summary (English)"
        type: text
      - name: body_en
        label: "Article (English)"
        type: rich-text
      - name: title_ru
        label: "Title (Русский)"
        type: string
      - name: description_ru
        label: "Summary (Русский)"
        type: text
      - name: body_ru
        label: "Article (Русский)"
        type: rich-text
  - name: blog_settings
    label: Blogseite
    type: file
    path: _data/blog.yml
    format: yaml
    fields:
      - name: title
        label: Überschrift
        type: string
        required: true
      - name: intro
        label: Einführung
        type: text
        required: true
      - name: title_en
        label: "title (English)"
        type: string
      - name: intro_en
        label: "intro (English)"
        type: text
      - name: title_ru
        label: "title (Русский)"
        type: string
      - name: intro_ru
        label: "intro (Русский)"
        type: text
